services:
  terraform:
    image: hashicorp/terraform:1.13.3
    container_name: tf
    working_dir: /workspace
    volumes:
      - ../terraform/:/workspace:rw
      - tfstate:/workspace/.terraform
      - tfplugin-cache:/root/.terraform.d/plugin-cache
      - ${HOME}/.aws:/root/.aws:ro
      - ${HOME}/.ssh:/root/.ssh:ro
    environment:
      AWS_SDK_LOAD_CONFIG: "1"
      AWS_PROFILE: "${AWS_PROFILE:-default}"
      AWS_REGION: "${AWS_REGION:-us-east-1}"
      TF_PLUGIN_CACHE_DIR: /root/.terraform.d/plugin-cache
      TF_INPUT: "0"
    entrypoint: [ "tail", "-f", "/.dockerenv" ]

volumes:
  tfstate:
  tfplugin-cache: